"""
异步轮询负载均衡器 - 支持用户粘性会话 + OpenAI流式 + 全性能监控(TTFT/TPOT/P50/P99)
功能：
  1. 用户粘性：同一个用户永远路由到同一个worker，最大化KV Cache命中率
  2. 兼容原有/generate接口
  3. 兼容OpenAI流式/v1/chat/completions
  4. 自动健康检查 + 故障转移
  5. 实时统计：TTFT、TPOT、平均延迟、P50、P99
  6. Prometheus 采集配置 Grafana 仪表盘
"""
import argparse
import asyncio
import os
import time
from itertools import cycle
from typing import List, Dict

import aiohttp
import uvicorn
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import StreamingResponse
from fastapi.responses import PlainTextResponse

from pydantic import BaseModel

# ==========================================
# 【Prometheus 监控依赖导入】
# ==========================================
from prometheus_client import (
    Counter,      # 计数器：请求数、错误数、token数
    Gauge,        # 仪表盘：健康状态、活跃用户数
    Histogram,    # 直方图：延迟、TTFT、TPOT（支持计算P50/P99）
    generate_latest,
    CONTENT_TYPE_LATEST
)

# ===================== 导入集群限流&调度核心组件 =====================
# 早期拒绝器：用户Token/QPS/全局QPS/黑白名单/高负载拒绝
from .early_rejector import PredictiveEarlyRejector
# 负载打分器：7维GPU推理节点综合负载评分
from .load_predictor import WorkerLoadPredictor, WorkerMetrics
# SLO健康管控：延迟、队列、KV缓存阈值熔断
from .slo_enforcer import SLOEnforcer
# 路由策略管理器：粘性/负载最优/轮询策略统一管理
from .route_strategy import RouteStrategyManager, RoutePolicy


from dinollm.utils import init_logger

from .router_grpc import start_grpc_server


logger = init_logger(__name__,"router")




# 1. 请求总数计数器（按worker节点 + 接口类型分类）
REQUEST_TOTAL = Counter(
    "router_requests_total",
    "Total requests routed by worker",
    ["worker", "api_type"]
)

# 2. 错误总数计数器
ERROR_TOTAL = Counter(
    "router_errors_total",
    "Total errors by worker",
    ["worker"]
)

# 3. Worker健康状态（1=健康 0=不健康）
WORKER_HEALTHY = Gauge(
    "worker_healthy_status",
    "Worker healthy status (1=healthy,0=unhealthy)",
    ["worker"]
)

# 4. 活跃用户粘性会话数量
ACTIVE_USER_BINDINGS = Gauge(
    "router_active_user_bindings",
    "Active user sticky session bindings"
)

# 5. TTFT 首token响应时间（直方图，支持P50/P99）
TTFT_HISTOGRAM = Histogram(
    "router_ttft_ms",
    "Time to first token in ms",
    ["worker"],
    buckets=[10, 20, 30, 50, 100, 200, 300, 500, 800, 1000, 2000, 5000]
)

# 6. TPOT 每token生成时间（直方图）
TPOT_HISTOGRAM = Histogram(
    "router_tpot_ms",
    "Time per output token in ms",
    ["worker"],
    buckets=[5, 10, 20, 30, 50, 100, 200]
)

# 7. 请求总延迟
REQUEST_LATENCY = Histogram(
    "router_request_latency_ms",
    "Total request latency in ms",
    ["worker"],
    buckets=[100, 300, 500, 1000, 3000, 5000, 10000,15000,20000]
)

# 8. 生成Token总数
GENERATED_TOKENS_TOTAL = Counter(
    "router_generated_tokens_total",
    "Total tokens generated by worker",
    ["worker"]
)

# 创建FastAPI应用实例
app = FastAPI(title="ML Inference Router (Sticky + OpenAI + Metrics)")

# 原有接口请求数据模型（完全保留）
class GenerateRequest(BaseModel):
    prompt: str
    max_new_tokens: int = 50

class RouterState:
    """
    路由状态管理（核心）
    管理：worker健康状态、用户粘性绑定、全链路监控统计、并发安全
    """
    def __init__(self, worker_urls: List[str]):
        self.all_workers = worker_urls
        self.healthy_workers: List[str] = list(worker_urls)
        self._cycle = cycle(self.healthy_workers)
        self._router_lock = asyncio.Lock()    # 路由：用户绑定、健康节点
        self._stats_lock = asyncio.Lock()     # 统计：请求数、TTFT、TPOT、tokens

        # 用户 -> worker 绑定映射（粘性会话核心）
        self.user_to_worker: Dict[str, str] = {}

        # 每个worker的全维度统计指标
        self.stats: Dict[str, dict] = {}
        for url in worker_urls:
            self.stats[url] = {
                # 基础请求统计
                "requests": 0,
                "errors": 0,
                "total_latency_ms": 0.0,

                # 流式指标存储
                "ttft_list": [],       # 首token时间列表
                "tpot_list": [],       # 每token时延列表
                "total_tokens": 0      # 总生成token数
            }
        # ====================== 新增：调度&限流核心实例初始化 ======================
        # 1. 节点负载打分器
        self.load_predictor = WorkerLoadPredictor()
        # 2. SLO服务等级熔断管控
        self.slo_enforcer = SLOEnforcer()
        # 3. 多策略路由管理器
        self.route_manager = RouteStrategyManager(self.load_predictor)
        # 4. 全维度早期拒绝器【核心：用户Token/用户QPS/全局QPS/黑白名单】
        self.early_rejector = PredictiveEarlyRejector(
            max_global_qps=400,        # 全局集群最大QPS
            max_user_qps=2,            # 单用户每秒最大请求数
            max_user_token_quota=100000000, # 单用户累计最大Token额度
            high_load_score_threshold=0.9  # 节点负载分数超过0.75直接拒绝
        )

        # 存储每个worker实时7维推理指标
        self.worker_realtime_metrics: Dict[str, WorkerMetrics] = {}
        for url in worker_urls:
            self.worker_realtime_metrics[url] = WorkerMetrics(
                worker_id=url,
                gpu_flops_total=180.0,
                kv_cache_free_gb=32.0,
                prefill_queue_len=0,
                decode_queue_len=0,
                wait_prefill_queue_len=0,
                ttft_ms=500.0,
                tpot_ms=40.0
            )
        # ==========================================================================

    def next_worker(self) -> str:
        """普通轮询：获取下一个健康worker"""
        if not self.healthy_workers:
            raise RuntimeError("No healthy workers available")
        return next(self._cycle)

    async def get_worker_for_user(self, user_id: str) -> str:
        """
        【粘性会话核心】
        根据user_id获取绑定的worker
        规则：
            1. 已绑定且worker健康 → 直接返回
            2. 已绑定但worker挂了 → 删除旧绑定，重新分配
            3. 未绑定 → 轮询分配并记录
        """
        async with self._router_lock:
            if not self.healthy_workers:
                raise RuntimeError("No healthy workers available")

            # 用户已绑定，且worker健康
            if user_id in self.user_to_worker:
                worker = self.user_to_worker[user_id]
                if worker in self.healthy_workers:
                    return worker
                # 绑定的worker已下线，删除绑定
                del self.user_to_worker[user_id]

            # 新用户 / 需重分配：轮询选一个worker
            new_worker = next(self._cycle)
            self.user_to_worker[user_id] = new_worker
            print(f"[Router] 新用户绑定: {user_id} -> {new_worker}")
            return new_worker
        
        
    # ===================== 新增：智能选节点 + 全量限流校验统一入口 =====================
    async def select_available_worker(self, user_id: str, expect_token_num: int) -> str:
        """
        整合流程：
        1. 筛选SLO健康节点
        2. 按用户粘性优先调度
        3. 计算节点负载分数
        4. 执行早期拒绝：用户Token超限/用户QPS超限/全局QPS超限/黑名单/节点高负载
        """
        # 取出所有健康节点实时指标
        all_health_metrics = [
            self.worker_realtime_metrics[w]
            for w in self.healthy_workers
            if w in self.worker_realtime_metrics
        ]
        if not all_health_metrics:
            raise HTTPException(status_code=503, detail="暂无可用推理节点")

        # 过滤仅保留正常+警告状态节点，封禁节点直接剔除
        valid_workers = self.slo_enforcer.get_healthy_workers(all_health_metrics)
        if not valid_workers:
            raise HTTPException(status_code=503, detail="所有节点均已触发SLO限流")

        # 使用粘性策略选择目标节点
        target_worker = self.route_manager.select_worker(
            policy=RoutePolicy.USER_STICKY,
            worker_metrics_list=valid_workers,
            user_id=user_id
        )
        if not target_worker:
            raise HTTPException(status_code=503, detail="节点调度失败")

        # 获取选中节点负载分数
        load_score = self.load_predictor.calc_node_score(self.worker_realtime_metrics[target_worker])

        # ========== 核心限流校验：全部走用户维度控制 ==========
        is_reject, reject_reason = self.early_rejector.should_reject(
            user_id=user_id,
            token_count=expect_token_num,
            worker_load_score=load_score
        )
        if is_reject:
            raise HTTPException(status_code=429, detail=f"请求受限：{reject_reason}")

        # 绑定用户与会话节点
        self.route_manager.bind_user_worker(user_id, target_worker)
        return target_worker
    # =================================================================================

    async def record(self, url: str, latency_ms: float):
        """记录普通请求（非流式）"""
        async with self._stats_lock:
            self.stats[url]["requests"] += 1
            self.stats[url]["total_latency_ms"] += latency_ms

        REQUEST_TOTAL.labels(worker=url, api_type="generate").inc()
        REQUEST_LATENCY.labels(worker=url).observe(latency_ms)

    async def record_error(self, url: str):
        """记录请求失败"""
        async with self._stats_lock:
            self.stats[url]["errors"] += 1

        ERROR_TOTAL.labels(worker=url).inc()

    async def record_stream_metrics(self, url: str, ttft_ms: float, total_tokens: int, total_latency_ms: float):
        """
        记录流式请求指标
        :param url: worker地址
        :param ttft_ms: 首token时间
        :param total_tokens: 总生成token数
        :param total_latency_ms: 总耗时
        """
        async with self._stats_lock:
            stat = self.stats[url]
            stat["requests"] += 1
            stat["ttft_list"].append(ttft_ms)
            stat["total_tokens"] += total_tokens
            stat["total_latency_ms"] += total_latency_ms

            # 计算TPOT：除首token外，平均每token耗时
            if total_tokens > 1:
                output_time = total_latency_ms - ttft_ms
                tpot = output_time / (total_tokens - 1)
                stat["tpot_list"].append(tpot)

            # 限制列表长度，防止内存无限增长
            max_records = 10000
            stat["ttft_list"] = stat["ttft_list"][-max_records:]
            stat["tpot_list"] = stat["tpot_list"][-max_records:]
        REQUEST_TOTAL.labels(worker=url, api_type="openai").inc()
        TTFT_HISTOGRAM.labels(worker=url).observe(ttft_ms)
        REQUEST_LATENCY.labels(worker=url).observe(total_latency_ms)
        GENERATED_TOKENS_TOTAL.labels(worker=url).inc(total_tokens)

        if total_tokens > 1:
            tpot = (total_latency_ms - ttft_ms) / (total_tokens - 1)
            TPOT_HISTOGRAM.labels(worker=url).observe(tpot)   
        

    def _compute_percentile(self, data, percent):
        """计算百分位：P50/P99"""
        if not data:
            return 0.0
        sorted_data = sorted(data)
        idx = int(len(sorted_data) * percent / 100)
        return sorted_data[idx]

    def mark_unhealthy(self, url: str):
        if url in self.healthy_workers:
            self.healthy_workers.remove(url)
            self._cycle = cycle(self.healthy_workers) if self.healthy_workers else iter([])
            print(f"[Router] Worker {url} 已下线. 健康节点数: {len(self.healthy_workers)}")

    def mark_healthy(self, url: str):
        if url not in self.healthy_workers:
            self.healthy_workers.append(url)
            self._cycle = cycle(self.healthy_workers)
            print(f"[Router] Worker {url} 已恢复. 健康节点数: {len(self.healthy_workers)}")

# 全局路由状态对象
state: RouterState = None

async def health_check_loop(interval: int = 5):
    """后台定时健康检查：每5秒检查所有worker"""
    async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=3)) as session:
        while True:
            for url in state.all_workers:
                try:
                    async with session.get(f"{url}/health") as resp:
                        if resp.status == 200:
                            # # 拉取worker上报的7维实时负载指标
                            # try:
                            #     worker_data = await resp.json()
                            #     state.worker_realtime_metrics[url] = WorkerMetrics(
                            #         worker_id=url,
                            #         gpu_flops_total=worker_data.get("gpu_flops_total", 180.0),
                            #         kv_cache_free_gb=worker_data.get("kv_cache_free_gb", 32.0),
                            #         prefill_queue_len=worker_data.get("prefill_queue_len", 0),
                            #         decode_queue_len=worker_data.get("decode_queue_len", 0),
                            #         wait_prefill_queue_len=worker_data.get("wait_prefill_queue_len", 0),
                            #         ttft_ms=worker_data.get("ttft_ms", 500.0),
                            #         tpot_ms=worker_data.get("tpot_ms", 40.0)
                            #     )
                            # except Exception:
                            #     pass
                            state.mark_healthy(url)
                        else:
                            state.mark_unhealthy(url)
                except Exception:
                    state.mark_unhealthy(url)
            await asyncio.sleep(interval)
            # 定时清理过期QPS统计与无效用户Token记录，防止内存溢出
            state.early_rejector.clean_expired_qps()

@app.on_event("startup")
async def startup():
    """服务启动时自动执行：启动健康检查任务"""
    asyncio.create_task(health_check_loop())
    print(f"[Router] 启动成功！工作节点: {state.all_workers}")
    asyncio.create_task(start_grpc_server(state))

@app.get("/health")
async def health():
    """路由健康检查接口"""
    return {
        "status": "ok",
        "healthy_workers": state.healthy_workers,
        "all_workers": state.all_workers,
        "active_user_bindings": len(state.user_to_worker),
        "worker_stats": state.stats
    }
    
# ==============================
# Prometheus 指标接口
# ==============================
@app.get("/metrics", response_class=PlainTextResponse)
async def metrics():
    return generate_latest()


@app.post("/generate")
async def generate(req: GenerateRequest):
    """原有同步生成接口：等待全部结果返回"""
    if not state.healthy_workers:
        raise HTTPException(status_code=503, detail="No healthy workers available")

    worker_url = state.next_worker()
    start = time.time()

    async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=60)) as session:
        try:
            async with session.post(
                f"{worker_url}/generate",
                json={"prompt": req.prompt, "max_new_tokens": req.max_new_tokens}
            ) as resp:
                if resp.status != 200:
                    await state.record_error(worker_url)
                    raise HTTPException(status_code=resp.status, detail=await resp.text())

                result = await resp.json()
                latency = (time.time() - start) * 1000
                await state.record(worker_url, latency)

                result["routed_to"] = worker_url
                result["router_latency_ms"] = latency
                return result

        except aiohttp.ClientError as e:
            await state.record_error(worker_url)
            state.mark_unhealthy(worker_url)
            raise HTTPException(status_code=503, detail=f"Worker {worker_url} 无法连接: {str(e)}")

# ==============================
# OpenAI 流式接口 + 粘性会话 + 全指标监控
# ==============================
@app.post("/v1/chat/completions")
async def openai_chat_completions(request: Request):
    if not state.healthy_workers:
        raise HTTPException(status_code=503, detail="No healthy workers available")

    body = await request.json()
    user_id = body.get("user") or body.get("session_id") or request.client.host or "anonymous"
    # 取请求内最大生成长度作为预估Token消耗
    pre_estimate_tokens = body.get("max_tokens", 256)
    
    # worker_url = await state.get_worker_for_user(user_id)
    
    # ================== 新加 ==================
    is_new = body.get("is_new_session", False)
    if is_new:
        logger.info(f"新会话请求，清除用户绑定: {user_id}")
        state.route_manager.unbind_user_worker(user_id)
    # ===========================================
    
    # 统一经过：粘性调度 + SLO过滤 + 用户Token/QPS/全局QPS限流
    worker_url = await state.select_available_worker(user_id, pre_estimate_tokens)

    # 计时
    start_all = time.time()
    ttft_recorded = False
    ttft_ms = 0.0
    total_tokens = 0

    try:
        async def stream_forward():
            nonlocal ttft_recorded, ttft_ms, total_tokens

            async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=120)) as session:
                async with session.post(
                    f"{worker_url}/v1/chat/completions",
                    json=body,
                    headers=dict(request.headers)
                ) as resp:

                    async for chunk in resp.content.iter_chunked(1024):
                        # 第一次返回数据：记录TTFT
                        if not ttft_recorded:
                            ttft_ms = (time.time() - start_all) * 1000
                            ttft_recorded = True
                        else:
                            total_tokens += 1

                        yield chunk

            # 请求结束：记录完整指标
            total_latency = (time.time() - start_all) * 1000
            await state.record_stream_metrics(
                url=worker_url,
                ttft_ms=ttft_ms,
                total_tokens=total_tokens,
                total_latency_ms=total_latency
            )

        return StreamingResponse(
            stream_forward(),
            media_type="text/event-stream"
        )

    except aiohttp.ClientError as e:
        await state.record_error(worker_url)
        state.mark_unhealthy(worker_url)
        raise HTTPException(status_code=503, detail=f"Worker {worker_url} 无法连接")

# ==============================
# 监控统计接口：输出 TTFT / TPOT / P50 / P99
# ==============================
@app.get("/stats")
async def stats():
    """
    全维度监控面板
    包含：请求数、错误数、平均延迟、TTFT、TPOT、P50、P99
    """
    summary = {}
    for url, s in state.stats.items():
        req_count = s["requests"]
        err_count = s["errors"]
        avg_lat = s["total_latency_ms"] / req_count if req_count > 0 else 0.0

        # TTFT 统计
        ttft_list = s["ttft_list"]
        avg_ttft = sum(ttft_list) / len(ttft_list) if ttft_list else 0.0
        p50_ttft = state._compute_percentile(ttft_list, 50)
        p99_ttft = state._compute_percentile(ttft_list, 99)

        # TPOT 统计
        tpot_list = s["tpot_list"]
        avg_tpot = sum(tpot_list) / len(tpot_list) if tpot_list else 0.0
        p50_tpot = state._compute_percentile(tpot_list, 50)
        p99_tpot = state._compute_percentile(tpot_list, 99)

        summary[url] = {
            "requests": req_count,
            "errors": err_count,
            "avg_total_latency_ms": round(avg_lat, 2),
            "total_tokens_generated": s["total_tokens"],
            "ttft_ms": {
                "avg": round(avg_ttft, 2),
                "p50": round(p50_ttft, 2),
                "p99": round(p99_ttft, 2)
            },
            "tpot_ms": {
                "avg": round(avg_tpot, 4),
                "p50": round(p50_tpot, 4),
                "p99": round(p99_tpot, 4)
            }
        }

    return {
        "workers": summary,
        "healthy_workers": state.healthy_workers,
        "active_user_bindings": len(state.user_to_worker)
    }

# ==============================
# 启动入口
# ==============================
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="分布式DinoLLM推理路由")
    parser.add_argument("--workers", nargs="+", required=True, help="worker节点地址列表")
    parser.add_argument("--port", type=int, default=8080, help="路由服务端口")
    args = parser.parse_args()

    state = RouterState(args.workers)
    uvicorn.run(app, host="0.0.0.0", port=args.port)